name: Docker

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}:0.0.1
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v1
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Use NPM to install dependencies
          uses: actions/setup-node@v1
          with:
            node-version: '14.x'
        - run: npm install

        - name: Build application
          run: npm run build

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME \
              --platform managed \
              --region europe-west1 \
              --allow-unauthenticated \
              --min-instances 1 \
              --max-instances 2 \
              --memory 512Mi \
              --cpu 1 \
              --port 3000 \
              --set-env-vars "" \
              --service-account=${{ secrets.CLOUD_RUN_EXECUTOR_SERVICE_ACCOUNT }}