name: Testing and update Codecov

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  update-codecov:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer tous les tags

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v13.7.2
        env: 
          GCP_SA_KEY: ${{ secrets.FIREBASE_SA_KEY }}

      - name: Use NPM to install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: npm install

      - name: Start of Firebase emulator in a background process
        run: npm run firebase:emulator &

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          file: ./coverage/lcov.info
          fail_ci_if_error: true
