name: Testing and update Codecov

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  update-codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer tous les tags

      - name: Use NPM to install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: npm install

      - name: Build application
        run: npm run build

      - name: Start of Firebase emulator in a background process
        run: npm run firebase:emulator &

      - name: Run tests
        run: npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          fail_ci_if_error: true
